---
- hosts: all
  tasks:
    - name: add repository
      apt:
        name: "*"
        update_cache: yes
  
    - name: upgrade dist
      apt:
        upgrade: dist

    - name: install required package
      apt: 
        name: "{{ packages }}"
      vars:
        packages:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common

    - apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
        state: present

    - name: Add apt sigining key
      apt_key:
        id: 0EBFCD88
        url: https://download.docker.com/linux/ubuntu/gpg 

    - name: update cache
      apt:
        name: "*"
        update_cache: yes

    - name: install docker 17.03.2
      apt:
        name: "docker-ce=17.03.2~ce-0~ubuntu-xenial"
        state: "present"
        update_cache: "yes"

    
    - name: TestNaja
      apt:
        name: OKja